### ISSUE TITLE
It's a fake and unfinished work.

### ISSUE THREAD

**Issue by connLAN** [siyueshiqi/LAN_IM#1]
Hello siyueshiqi,  I cloned your LAN_IM, and try to porting it to QT5 and english version. It looks you have spend much time on it. 

But I am not clear : why you stop update it?  It is fake , client can only connect on the same ip of the server. And there is no line code to  do any database maintain , such as create database and tables. Even not to say  project documents.

In fact this could be a greate project if you continue work on it. And it could be a good example on QT programming.

Hope you can restart this work.

**Comment by siyueshiqi** [comment]
Thanks very much for your attention. This is my undergraduate graduation project and I develop it with QT4 about 3 years ago.

If you server doesn't have public IP, client and server must in the same LAN, then client can connect to the Server. If you server have public IP, client can connect to the server, even they are not in the same LAN.
In the Login Window, you can configure the server IP. If you doesn't configure it, the default server IP is localhost(127.0.0.1).

And you are right. I am sorry. There is no any code to create database and tables. But I provide client.sql and server.sql for you to create Database and Tables.

If you are interested in thie project, you can work on it. If you have only question, you can ask to me. Thanks again.

**Comment by connLAN** [comment]
Yes, I find the place to input server ip and port, and it works  :)  

I'll and some document to introduce it later.

Anyway , it looks good as a demo.

**Comment by siyueshiqi** [comment]
Thank you. If you have any questions, you can ask to me directly. My email is **frazq10@163.com**. My QQ is **416470485**.
